exports.orderStatus = {
  1: "New",
  2: "Confirmed",
  3: "Success",
  4: "Failed",
};

exports.orders = [
  {
    id: 1,
    customer_name: "Bax Matyushkin",
    email: "bmatyushkin0@flavors.me",
    gender: "Non-binary",
    customer_phone: "851-419-6179",
    total_price: "$386.25",
    status: 1,
  },
  {
    id: 2,
    customer_name: "Milli Wozencroft",
    email: "mwozencroft1@tinypic.com",
    gender: "Female",
    customer_phone: "777-521-8902",
    total_price: "$16.33",
    status: 4,
  },
  {
    id: 3,
    customer_name: "Boote Cosford",
    email: "bcosford2@miitbeian.gov.cn",
    gender: "Bigender",
    customer_phone: "146-882-8190",
    total_price: "$307.63",
    status: 3,
  },
  {
    id: 4,
    customer_name: "Chrissy Bearns",
    email: "cbearns3@studiopress.com",
    gender: "Female",
    customer_phone: "708-488-1968",
    total_price: "$1345.78",
    status: 3,
  },
  {
    id: 5,
    customer_name: "Sheela Langston",
    email: "slangston4@dyndns.org",
    gender: "Female",
    customer_phone: "668-203-8323",
    total_price: "$485.15",
    status: 3,
  },
  {
    id: 6,
    customer_name: "Jacinthe Roddie",
    email: "jroddie5@photobucket.com",
    gender: "Female",
    customer_phone: "216-956-1881",
    total_price: "$1941.93",
    status: 1,
  },
  {
    id: 7,
    customer_name: "Palm Menier",
    email: "pmenier6@japanpost.jp",
    gender: "Male",
    customer_phone: "368-167-2978",
    total_price: "$390.55",
    status: 1,
  },
  {
    id: 8,
    customer_name: "Iver Duffil",
    email: "iduffil7@istockphoto.com",
    gender: "Male",
    customer_phone: "245-764-4524",
    total_price: "$716.82",
    status: 1,
  },
  {
    id: 9,
    customer_name: "Clarette Bandey",
    email: "cbandey8@prlog.org",
    gender: "Female",
    customer_phone: "196-832-2327",
    total_price: "$523.71",
    status: 4,
  },
  {
    id: 10,
    customer_name: "Flora Beaufoy",
    email: "fbeaufoy9@fema.gov",
    gender: "Female",
    customer_phone: "586-824-2914",
    total_price: "$968.96",
    status: 4,
  },
  {
    id: 11,
    customer_name: "Vitia Radbone",
    email: "vradbonea@artisteer.com",
    gender: "Female",
    customer_phone: "200-267-3545",
    total_price: "$1621.84",
    status: 4,
  },
  {
    id: 12,
    customer_name: "Rebekkah Houtby",
    email: "rhoutbyb@economist.com",
    gender: "Female",
    customer_phone: "309-417-2392",
    total_price: "$1051.42",
    status: 3,
  },
  {
    id: 13,
    customer_name: "Morgan Thomson",
    email: "mthomsonc@sfgate.com",
    gender: "Male",
    customer_phone: "114-688-4127",
    total_price: "$1124.21",
    status: 3,
  },
  {
    id: 14,
    customer_name: "Davidson Fysh",
    email: "dfyshd@bing.com",
    gender: "Male",
    customer_phone: "304-521-3275",
    total_price: "$635.82",
    status: 4,
  },
  {
    id: 15,
    customer_name: "Aimil Edmund",
    email: "aedmunde@stumbleupon.com",
    gender: "Female",
    customer_phone: "353-243-8373",
    total_price: "$972.58",
    status: 3,
  },
  {
    id: 16,
    customer_name: "Kylie Bellchamber",
    email: "kbellchamberf@dailymail.co.uk",
    gender: "Male",
    customer_phone: "999-747-7958",
    total_price: "$15.19",
    status: 4,
  },
  {
    id: 17,
    customer_name: "Gearalt Gundry",
    email: "ggundryg@sphinn.com",
    gender: "Male",
    customer_phone: "535-704-8961",
    total_price: "$1748.49",
    status: 3,
  },
  {
    id: 18,
    customer_name: "Laurens Illingworth",
    email: "lillingworthh@usnews.com",
    gender: "Male",
    customer_phone: "494-358-6649",
    total_price: "$347.82",
    status: 3,
  },
  {
    id: 19,
    customer_name: "Meir Weld",
    email: "mweldi@studiopress.com",
    gender: "Male",
    customer_phone: "129-911-6062",
    total_price: "$908.06",
    status: 2,
  },
  {
    id: 20,
    customer_name: "Blane Ambrogi",
    email: "bambrogij@gmpg.org",
    gender: "Agender",
    customer_phone: "900-736-2883",
    total_price: "$1566.72",
    status: 2,
  },
  {
    id: 21,
    customer_name: "Mariellen Bradley",
    email: "mbradleyk@ovh.net",
    gender: "Female",
    customer_phone: "609-179-2545",
    total_price: "$717.17",
    status: 3,
  },
  {
    id: 22,
    customer_name: "Dall Pridie",
    email: "dpridiel@github.com",
    gender: "Male",
    customer_phone: "752-414-0790",
    total_price: "$1597.64",
    status: 3,
  },
  {
    id: 23,
    customer_name: "Borg Schachter",
    email: "bschachterm@bravesites.com",
    gender: "Male",
    customer_phone: "355-675-4630",
    total_price: "$616.82",
    status: 4,
  },
  {
    id: 24,
    customer_name: "Ula Bernini",
    email: "uberninin@w3.org",
    gender: "Female",
    customer_phone: "535-877-1098",
    total_price: "$204.20",
    status: 1,
  },
  {
    id: 25,
    customer_name: "Diann Harty",
    email: "dhartyo@amazon.co.jp",
    gender: "Female",
    customer_phone: "149-370-1137",
    total_price: "$249.48",
    status: 4,
  },
  {
    id: 26,
    customer_name: "Georgena Shall",
    email: "gshallp@prlog.org",
    gender: "Female",
    customer_phone: "312-992-9155",
    total_price: "$1144.20",
    status: 4,
  },
  {
    id: 27,
    customer_name: "Eden Pawelec",
    email: "epawelecq@nih.gov",
    gender: "Female",
    customer_phone: "948-937-7739",
    total_price: "$1198.63",
    status: 2,
  },
  {
    id: 28,
    customer_name: "Godiva Dyson",
    email: "gdysonr@nbcnews.com",
    gender: "Female",
    customer_phone: "163-253-8846",
    total_price: "$431.48",
    status: 1,
  },
  {
    id: 29,
    customer_name: "Patsy Bourcq",
    email: "pbourcqs@newsvine.com",
    gender: "Male",
    customer_phone: "896-633-3701",
    total_price: "$547.35",
    status: 3,
  },
  {
    id: 30,
    customer_name: "Lotty Creebo",
    email: "lcreebot@washingtonpost.com",
    gender: "Female",
    customer_phone: "636-862-6863",
    total_price: "$1926.59",
    status: 1,
  },
  {
    id: 31,
    customer_name: "Maxi Bouldstridge",
    email: "mbouldstridgeu@tinyurl.com",
    gender: "Female",
    customer_phone: "131-552-5693",
    total_price: "$785.25",
    status: 1,
  },
  {
    id: 32,
    customer_name: "Hugibert Orrett",
    email: "horrettv@dropbox.com",
    gender: "Genderfluid",
    customer_phone: "929-836-8363",
    total_price: "$188.14",
    status: 1,
  },
  {
    id: 33,
    customer_name: "Emmery Copson",
    email: "ecopsonw@gov.uk",
    gender: "Male",
    customer_phone: "477-994-7303",
    total_price: "$1901.68",
    status: 1,
  },
  {
    id: 34,
    customer_name: "Eloisa Costard",
    email: "ecostardx@mlb.com",
    gender: "Female",
    customer_phone: "265-742-0769",
    total_price: "$1018.64",
    status: 4,
  },
  {
    id: 35,
    customer_name: "Ibbie Georg",
    email: "igeorgy@hhs.gov",
    gender: "Female",
    customer_phone: "980-924-1293",
    total_price: "$534.93",
    status: 1,
  },
  {
    id: 36,
    customer_name: "Rusty Cradock",
    email: "rcradockz@ibm.com",
    gender: "Male",
    customer_phone: "773-314-0923",
    total_price: "$534.67",
    status: 1,
  },
  {
    id: 37,
    customer_name: "Ray Merwede",
    email: "rmerwede10@smugmug.com",
    gender: "Male",
    customer_phone: "357-922-7670",
    total_price: "$784.15",
    status: 2,
  },
  {
    id: 38,
    customer_name: "Colly Kynaston",
    email: "ckynaston11@toplist.cz",
    gender: "Female",
    customer_phone: "644-838-2908",
    total_price: "$1155.45",
    status: 4,
  },
  {
    id: 39,
    customer_name: "Boycie Teggart",
    email: "bteggart12@nymag.com",
    gender: "Male",
    customer_phone: "136-134-6748",
    total_price: "$1269.36",
    status: 1,
  },
  {
    id: 40,
    customer_name: "Cosimo Coite",
    email: "ccoite13@biblegateway.com",
    gender: "Genderqueer",
    customer_phone: "290-730-7872",
    total_price: "$635.75",
    status: 1,
  },
  {
    id: 41,
    customer_name: "Burg Lewisham",
    email: "blewisham14@mail.ru",
    gender: "Male",
    customer_phone: "637-178-6096",
    total_price: "$685.47",
    status: 1,
  },
  {
    id: 42,
    customer_name: "Lyndell Cattrell",
    email: "lcattrell15@unesco.org",
    gender: "Female",
    customer_phone: "880-244-0967",
    total_price: "$678.61",
    status: 3,
  },
  {
    id: 43,
    customer_name: "Eddie Oswald",
    email: "eoswald16@hud.gov",
    gender: "Male",
    customer_phone: "716-357-7534",
    total_price: "$489.62",
    status: 4,
  },
  {
    id: 44,
    customer_name: "Adrian Arnaudon",
    email: "aarnaudon17@nbcnews.com",
    gender: "Female",
    customer_phone: "584-352-6403",
    total_price: "$554.21",
    status: 1,
  },
  {
    id: 45,
    customer_name: "Ralph Stockin",
    email: "rstockin18@illinois.edu",
    gender: "Male",
    customer_phone: "245-349-3382",
    total_price: "$337.40",
    status: 1,
  },
  {
    id: 46,
    customer_name: "Stephi Clericoates",
    email: "sclericoates19@theatlantic.com",
    gender: "Female",
    customer_phone: "523-249-6511",
    total_price: "$251.46",
    status: 3,
  },
  {
    id: 47,
    customer_name: "Martie Rawes",
    email: "mrawes1a@icq.com",
    gender: "Male",
    customer_phone: "615-560-6125",
    total_price: "$809.08",
    status: 2,
  },
  {
    id: 48,
    customer_name: "Silva Kondratowicz",
    email: "skondratowicz1b@feedburner.com",
    gender: "Female",
    customer_phone: "199-583-8078",
    total_price: "$42.68",
    status: 2,
  },
  {
    id: 49,
    customer_name: "Murdoch Micka",
    email: "mmicka1c@japanpost.jp",
    gender: "Male",
    customer_phone: "680-147-8379",
    total_price: "$468.80",
    status: 2,
  },
  {
    id: 50,
    customer_name: "Eldin Izkovici",
    email: "eizkovici1d@accuweather.com",
    gender: "Male",
    customer_phone: "697-497-9075",
    total_price: "$79.40",
    status: 4,
  },
  {
    id: 51,
    customer_name: "Hadleigh Ancliff",
    email: "hancliff1e@home.pl",
    gender: "Male",
    customer_phone: "472-352-8368",
    total_price: "$493.20",
    status: 2,
  },
  {
    id: 52,
    customer_name: "Rona Birkbeck",
    email: "rbirkbeck1f@example.com",
    gender: "Female",
    customer_phone: "873-116-8028",
    total_price: "$1371.64",
    status: 3,
  },
  {
    id: 53,
    customer_name: "Nicky Tutchell",
    email: "ntutchell1g@123-reg.co.uk",
    gender: "Female",
    customer_phone: "911-863-8349",
    total_price: "$42.84",
    status: 4,
  },
  {
    id: 54,
    customer_name: "Heath Hebdon",
    email: "hhebdon1h@ovh.net",
    gender: "Genderqueer",
    customer_phone: "796-595-3535",
    total_price: "$1612.27",
    status: 1,
  },
  {
    id: 55,
    customer_name: "Thaddus Lancett",
    email: "tlancett1i@google.nl",
    gender: "Male",
    customer_phone: "737-710-0690",
    total_price: "$19.13",
    status: 3,
  },
  {
    id: 56,
    customer_name: "Georgine Rowbrey",
    email: "growbrey1j@istockphoto.com",
    gender: "Female",
    customer_phone: "446-250-5120",
    total_price: "$521.32",
    status: 2,
  },
  {
    id: 57,
    customer_name: "Monica Lebrun",
    email: "mlebrun1k@census.gov",
    gender: "Female",
    customer_phone: "226-461-2665",
    total_price: "$950.96",
    status: 3,
  },
  {
    id: 58,
    customer_name: "Abeu Christon",
    email: "achriston1l@tinyurl.com",
    gender: "Male",
    customer_phone: "984-568-1037",
    total_price: "$1640.90",
    status: 2,
  },
  {
    id: 59,
    customer_name: "Karyl Sirmond",
    email: "ksirmond1m@hostgator.com",
    gender: "Female",
    customer_phone: "726-386-2448",
    total_price: "$808.25",
    status: 1,
  },
  {
    id: 60,
    customer_name: "Vivyan Badman",
    email: "vbadman1n@wp.com",
    gender: "Female",
    customer_phone: "405-800-3090",
    total_price: "$397.42",
    status: 3,
  },
  {
    id: 61,
    customer_name: "Davey Roony",
    email: "droony1o@lycos.com",
    gender: "Male",
    customer_phone: "488-983-3754",
    total_price: "$1388.89",
    status: 3,
  },
  {
    id: 62,
    customer_name: "Ulrica Wisher",
    email: "uwisher1p@deliciousdays.com",
    gender: "Female",
    customer_phone: "255-939-3983",
    total_price: "$476.46",
    status: 4,
  },
  {
    id: 63,
    customer_name: "Penelopa Hinckley",
    email: "phinckley1q@nifty.com",
    gender: "Female",
    customer_phone: "114-107-2699",
    total_price: "$528.86",
    status: 3,
  },
  {
    id: 64,
    customer_name: "Conway Sproul",
    email: "csproul1r@jigsy.com",
    gender: "Male",
    customer_phone: "216-943-9410",
    total_price: "$56.68",
    status: 4,
  },
  {
    id: 65,
    customer_name: "Gweneth Cuncliffe",
    email: "gcuncliffe1s@unesco.org",
    gender: "Female",
    customer_phone: "627-781-4775",
    total_price: "$117.21",
    status: 3,
  },
  {
    id: 66,
    customer_name: "Aile Blondell",
    email: "ablondell1t@amazon.co.jp",
    gender: "Polygender",
    customer_phone: "827-607-1153",
    total_price: "$985.91",
    status: 3,
  },
  {
    id: 67,
    customer_name: "Ricky Ferreres",
    email: "rferreres1u@dropbox.com",
    gender: "Female",
    customer_phone: "377-582-9353",
    total_price: "$1484.59",
    status: 3,
  },
  {
    id: 68,
    customer_name: "Isaiah Stoffersen",
    email: "istoffersen1v@delicious.com",
    gender: "Male",
    customer_phone: "609-690-5183",
    total_price: "$1728.95",
    status: 3,
  },
  {
    id: 69,
    customer_name: "Jenica Matys",
    email: "jmatys1w@example.com",
    gender: "Female",
    customer_phone: "606-296-4531",
    total_price: "$976.35",
    status: 4,
  },
  {
    id: 70,
    customer_name: "Xylia Nancekivell",
    email: "xnancekivell1x@wufoo.com",
    gender: "Female",
    customer_phone: "853-194-7360",
    total_price: "$231.90",
    status: 2,
  },
  {
    id: 71,
    customer_name: "Wendie Tawse",
    email: "wtawse1y@technorati.com",
    gender: "Female",
    customer_phone: "947-734-7475",
    total_price: "$1799.30",
    status: 2,
  },
  {
    id: 72,
    customer_name: "Andra Maberley",
    email: "amaberley1z@stumbleupon.com",
    gender: "Female",
    customer_phone: "807-966-9966",
    total_price: "$1155.76",
    status: 2,
  },
  {
    id: 73,
    customer_name: "Aurilia Dunnan",
    email: "adunnan20@ow.ly",
    gender: "Female",
    customer_phone: "791-352-1127",
    total_price: "$150.50",
    status: 4,
  },
  {
    id: 74,
    customer_name: "Dominik Squirrell",
    email: "dsquirrell21@ftc.gov",
    gender: "Male",
    customer_phone: "310-747-0198",
    total_price: "$1952.59",
    status: 4,
  },
  {
    id: 75,
    customer_name: "Rebecka Gansbuhler",
    email: "rgansbuhler22@cargocollective.com",
    gender: "Female",
    customer_phone: "443-562-7704",
    total_price: "$798.66",
    status: 4,
  },
  {
    id: 76,
    customer_name: "Ximenes Wandrey",
    email: "xwandrey23@studiopress.com",
    gender: "Polygender",
    customer_phone: "413-896-8840",
    total_price: "$417.57",
    status: 2,
  },
  {
    id: 77,
    customer_name: "Raimondo Lux",
    email: "rlux24@bloomberg.com",
    gender: "Male",
    customer_phone: "577-778-0858",
    total_price: "$337.25",
    status: 3,
  },
  {
    id: 78,
    customer_name: "Vanessa Ivkovic",
    email: "vivkovic25@usa.gov",
    gender: "Female",
    customer_phone: "552-437-9946",
    total_price: "$351.45",
    status: 2,
  },
  {
    id: 79,
    customer_name: "Alvis Milkeham",
    email: "amilkeham26@usa.gov",
    gender: "Male",
    customer_phone: "517-266-7261",
    total_price: "$848.11",
    status: 2,
  },
  {
    id: 80,
    customer_name: "Duane Colam",
    email: "dcolam27@wikia.com",
    gender: "Male",
    customer_phone: "134-154-1748",
    total_price: "$1166.46",
    status: 1,
  },
  {
    id: 81,
    customer_name: "Byrom Oager",
    email: "boager28@stanford.edu",
    gender: "Male",
    customer_phone: "895-208-8230",
    total_price: "$1968.04",
    status: 4,
  },
  {
    id: 82,
    customer_name: "Karlens Foggo",
    email: "kfoggo29@marriott.com",
    gender: "Male",
    customer_phone: "197-913-9830",
    total_price: "$585.36",
    status: 1,
  },
  {
    id: 83,
    customer_name: "Darnell Wickenden",
    email: "dwickenden2a@usatoday.com",
    gender: "Male",
    customer_phone: "219-776-5426",
    total_price: "$758.54",
    status: 1,
  },
  {
    id: 84,
    customer_name: "Rebeka Wyldish",
    email: "rwyldish2b@nyu.edu",
    gender: "Female",
    customer_phone: "637-550-2808",
    total_price: "$1086.70",
    status: 4,
  },
  {
    id: 85,
    customer_name: "Remus Feldmark",
    email: "rfeldmark2c@sitemeter.com",
    gender: "Male",
    customer_phone: "955-362-3873",
    total_price: "$1605.72",
    status: 2,
  },
  {
    id: 86,
    customer_name: "Isaac Dufour",
    email: "idufour2d@meetup.com",
    gender: "Male",
    customer_phone: "317-594-5701",
    total_price: "$1385.28",
    status: 4,
  },
  {
    id: 87,
    customer_name: "Raine Muff",
    email: "rmuff2e@mtv.com",
    gender: "Agender",
    customer_phone: "139-143-6787",
    total_price: "$1796.58",
    status: 2,
  },
  {
    id: 88,
    customer_name: "Marlo Goracci",
    email: "mgoracci2f@topsy.com",
    gender: "Male",
    customer_phone: "650-408-4071",
    total_price: "$482.68",
    status: 2,
  },
  {
    id: 89,
    customer_name: "Winifred Dundridge",
    email: "wdundridge2g@apple.com",
    gender: "Female",
    customer_phone: "569-821-9806",
    total_price: "$1836.05",
    status: 2,
  },
  {
    id: 90,
    customer_name: "Oralia Haddick",
    email: "ohaddick2h@sogou.com",
    gender: "Female",
    customer_phone: "651-228-4071",
    total_price: "$1609.56",
    status: 3,
  },
  {
    id: 91,
    customer_name: "Hyman McDirmid",
    email: "hmcdirmid2i@google.de",
    gender: "Male",
    customer_phone: "204-479-4694",
    total_price: "$563.35",
    status: 3,
  },
  {
    id: 92,
    customer_name: "Allyce Kindley",
    email: "akindley2j@mit.edu",
    gender: "Female",
    customer_phone: "100-439-6727",
    total_price: "$1530.48",
    status: 2,
  },
  {
    id: 93,
    customer_name: "Aldis Croom",
    email: "acroom2k@umich.edu",
    gender: "Male",
    customer_phone: "761-530-3181",
    total_price: "$1809.71",
    status: 2,
  },
  {
    id: 94,
    customer_name: "Chris Defraine",
    email: "cdefraine2l@example.com",
    gender: "Male",
    customer_phone: "725-673-2532",
    total_price: "$1105.80",
    status: 2,
  },
  {
    id: 95,
    customer_name: "Toiboid Demaine",
    email: "tdemaine2m@bluehost.com",
    gender: "Male",
    customer_phone: "493-745-5480",
    total_price: "$605.91",
    status: 4,
  },
  {
    id: 96,
    customer_name: "Gavan Callicott",
    email: "gcallicott2n@japanpost.jp",
    gender: "Male",
    customer_phone: "872-110-6869",
    total_price: "$494.11",
    status: 3,
  },
  {
    id: 97,
    customer_name: "Albrecht Mansbridge",
    email: "amansbridge2o@bizjournals.com",
    gender: "Male",
    customer_phone: "730-869-4342",
    total_price: "$1690.59",
    status: 1,
  },
  {
    id: 98,
    customer_name: "Carolann Gino",
    email: "cgino2p@skyrock.com",
    gender: "Female",
    customer_phone: "335-425-5371",
    total_price: "$163.13",
    status: 1,
  },
  {
    id: 99,
    customer_name: "Nathanial Armstead",
    email: "narmstead2q@sun.com",
    gender: "Agender",
    customer_phone: "163-414-2251",
    total_price: "$390.71",
    status: 4,
  },
  {
    id: 100,
    customer_name: "Aigneis Bestiman",
    email: "abestiman2r@trellian.com",
    gender: "Female",
    customer_phone: "897-610-8548",
    total_price: "$180.34",
    status: 4,
  },
];
